defaults:
  - agent: dqn
  - override hydra/job_logging: logger

env: CartPole-v0

num_episodes: 1000

device: cuda

plot: False

path: ???

multirun_num: 1
seed: 100

hydra:
  run:
    dir: outputs/${hydra.runtime.choices.agent}/${env}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/seed=${seed}
    subdir: ${env}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - env
          - multirun_num
          - seed
