_target_: agent.ddpg.DDPGAgent
obs_dim: ???
act_dim: ???
buffer_size: 1000000
min_size: 1000
batch_size: 100
gamma: 0.99
actor_lr: 0.001
critic_lr: 0.001
tau: 0.995
noise_scale: 0.1
update_steps: 50
explore_steps: 10000
