_target_: agent.ddpg.DDPGAgent
obs_dim: ???
act_dim: ???
buffer_size: 100000
min_size: 1000
batch_size: 32
gamma: 0.99
actor_lr: 0.0001
critic_lr: 0.0001
tau: 0.995
update_steps: 50
explore_steps: 1000
